#!/bin/bash

# Use 0 if need to avoid pylint failure and proceed to 'git commit'
EXIT_ON_WARNING_ERROR=1
PYLINT_ARGS="--rcfile=$(pwd)/.pylintrc"

#
# Check if pylint is installed
#
python -c "import pylint"
if [[ $? -ne 0 ]]
then
  	echo "$0: pylint not installed!"
	echo "$0: make install"
	exit 1
fi

#
# Check all directories inside repo 
#
git diff --staged --name-only HEAD | while read -r i; do 
    echo "$0: Checking file $i" 
    if [ ${i: -3} == ".py" ]
    then
        pylint $PYLINT_ARGS "$i"
        if [[ $? -ne 0 ]]
        then
            echo "$0: pylint failed in $i!"
            if [[ $EXIT_ON_WARNING_ERROR -eq 1 ]]
            then
                echo "$0: Stop iterating."
                exit 1
            fi
        fi
    fi
done
# Otherwise hook exits with 0
