version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-jessie
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -e ocean[tests]
      - run:
          name: Run Pytest
          command: |
            . venv/bin/activate
            cd ocean && pytest
