dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: '6.4.2'
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: '2.3.5'

# knative installations?
# helm install riff-incubator/istio --name istio --namespace istio-system --values http://riff-incubator.cfapps.io/values/values-istio-knative.yaml --set ingressgateway.service.type=NodePort
# helm install riff-incubator/knative-istio --name knative-istio --namespace istio-system --set knative.ingressgateway.service.type=NodePort
# helm install riff-incubator/knative-build --name knative-build --namespace knative-build
# helm install riff-incubator/knative-serving --name knative-serving --namespace knative-serving